# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: example.com
  secret_key_base: f74d5d9b0bdafbaac6aa25958bd0fca049976233b84776bb479de8669f3d6b3f497a5d8200950611edfc77591a850bf04e5653308ffb2ff58743d0912d7e16e4

test:
  secret_key_base: 00ed46753d3fc7cd69b30235f6be10e77bf7c3c1a6fb868ea5aa85b06ff7e24b10bad8de3ee8bfdbabd3e1970ce7e24438f04b48c196cf11c8a7f50e52760372

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
